service: veek

provider:
  architecture: arm64
  logRetentionInDays: 1
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  stage: ${opt:stage}
  timeout: 30
  versionFunctions: false

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    format: 'esm'
    minify: false
    platform: 'node'
    target: 'node18'
    watch:
      pattern: ['**/*.ts']

functions:
  checkin:
    handler: functions/checkin.handler
