service: veek

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: ${opt:stage}
  timeout: 30

plugins:
  - serverless-esbuild

functions:
  checkin:
    handler: functions/checkin.handler
